Repository ss220-space/arma3, pull requests merged in 2022-05, with the labels that each got.

#36 Обновление TFAR и добавление ACE
  missions/WarlordSS220.zargabad/cba_settings.sqf
  missions/WarlordSS220.zargabad/description.ext
  missions/WarlordSS220.zargabad/initPlayerLocal.sqf
  missions/WarlordSS220.zargabad/mission.sqm
  missions/WarlordSS220.zargabad/music/musicPlayer.sqf
  missions/WarlordSS220.zargabad/onPlayerRespawn.sqf
Labels: enhancement

#38 Дескрипшн и лодаут
  missions/WarlordSS220.zargabad/cfgRespawnInventory.hpp
  missions/WarlordSS220.zargabad/description.ext
Labels: enhancement

#42 Исправление ошибок и добавление фракций
  missions/WarlordSS220.zargabad/CfgFunctions.hpp
  missions/WarlordSS220.zargabad/cba_settings.sqf
  missions/WarlordSS220.zargabad/cfgRespawnInventory.hpp
  missions/WarlordSS220.zargabad/configs/CfgDebriefing.hpp
  missions/WarlordSS220.zargabad/configs/CfgFunctions.hpp
  missions/WarlordSS220.zargabad/configs/CfgMusic.hpp
  missions/WarlordSS220.zargabad/configs/CfgRemoteExec.hpp
  missions/WarlordSS220.zargabad/configs/CfgRoles.hpp
  missions/WarlordSS220.zargabad/configs/CfgWLFactionAssets.hpp
  missions/WarlordSS220.zargabad/configs/CfgWLRequisitionPresets.hpp
  missions/WarlordSS220.zargabad/configs/cfgRespawnInventory.hpp
  missions/WarlordSS220.zargabad/description.ext
  missions/WarlordSS220.zargabad/mission.sqm
Labels: bug, enhancement

#43 Удалена зависимость JSRS
  missions/WarlordSS220.zargabad/mission.sqm
Labels: bug

#44 Добавлены миномёты, ящики, новая техника.
  missions/WarlordSS220.zargabad/configs/CfgWLRequisitionPresets.hpp
Labels: enhancement, Conflict

#45 Сохранение фондов
  missions/WarlordSS220.zargabad/configs/CfgFunctions.hpp
  missions/WarlordSS220.zargabad/initPlayerLocal.sqf
  missions/WarlordSS220.zargabad/initServer.sqf
  missions/WarlordSS220.zargabad/scripts/remover.sqf
  missions/WarlordSS220.zargabad/scripts/serverSide/fn_Server_onConnected.sqf
  missions/WarlordSS220.zargabad/scripts/serverSide/fn_Server_teamRestrict.sqf
Labels: enhancement
